/** One CodeMirror theme that reads the app's CSS variables, so all four app themes just work. */
import { EditorView } from "@codemirror/view";

export const editorTheme = EditorView.theme({
  "&": {
    backgroundColor: "var(--editor-bg)",
    color: "var(--syn-text)",
    height: "100%",
    fontSize: "var(--editor-font-size, 14px)",
  },
  "&.cm-focused": { outline: "none" },
  ".cm-scroller": {
    fontFamily: "var(--editor-font-family, var(--font-mono))",
    lineHeight: "1.65",
    overflow: "auto",
  },
  ".cm-content": {
    padding: "14px 0 40vh 0",
    caretColor: "var(--editor-cursor)",
  },
  ".cm-line": { padding: "0 16px 0 8px" },
  ".cm-cursor, .cm-dropCursor": { borderLeft: "1.5px solid var(--editor-cursor)" },
  "&.cm-focused > .cm-scroller > .cm-selectionLayer .cm-selectionBackground, .cm-selectionBackground, .cm-content ::selection": {
    backgroundColor: "var(--sel) !important",
  },
  ".cm-activeLine": { backgroundColor: "var(--editor-active-line)" },
  ".cm-gutters": {
    backgroundColor: "var(--editor-gutter)",
    color: "var(--ink-4)",
    border: "none",
    borderRight: "1px solid var(--hair)",
    fontSize: "0.72em",
    minWidth: "0",
  },
  ".cm-lineNumbers .cm-gutterElement": { padding: "0 5px 0 7px", minWidth: "2.4em" },
  ".cm-foldGutter .cm-gutterElement": { padding: "0 3px 0 0", width: "0.9em" },
  ".cm-activeLineGutter": { backgroundColor: "transparent", color: "var(--ink-2)" },
  ".cm-foldGutter .cm-gutterElement span": { color: "var(--ink-4)", cursor: "pointer", transition: "color var(--dur-1) var(--ease)", fontSize: "0.9em" },
  ".cm-foldGutter .cm-gutterElement:hover": { color: "var(--accent)" },
  ".cm-foldPlaceholder": {
    backgroundColor: "var(--accent-soft)",
    border: "none",
    color: "var(--accent)",
    borderRadius: "4px",
    padding: "0 6px",
    margin: "0 4px",
  },
  ".cm-matchingBracket, &.cm-focused .cm-matchingBracket": {
    backgroundColor: "var(--accent-soft)",
    outline: "1px solid var(--accent-glow)",
    borderRadius: "2px",
  },
  ".cm-nonmatchingBracket, &.cm-focused .cm-nonmatchingBracket": { backgroundColor: "var(--err-soft)" },
  ".cm-searchMatch": { backgroundColor: "var(--editor-match)", borderRadius: "2px" },
  ".cm-searchMatch.cm-searchMatch-selected": { backgroundColor: "var(--accent-glow)" },
  ".cm-selectionMatch": { backgroundColor: "var(--accent-softer)" },
  ".cm-tooltip": {
    backgroundColor: "var(--bg-3)",
    color: "var(--ink-1)",
    border: "1px solid var(--hair-2)",
    borderRadius: "var(--r-md)",
    boxShadow: "var(--shadow-2)",
    fontFamily: "var(--font-ui)",
    fontSize: "var(--text-xs)",
    overflow: "hidden",
  },
  ".cm-tooltip .cm-tooltip-arrow:before, .cm-tooltip .cm-tooltip-arrow:after": { display: "none" },
  ".cm-tooltip-autocomplete": {
    "& > ul": { fontFamily: "var(--font-mono)", fontSize: "0.9em", maxHeight: "16em" },
    "& > ul > li": { padding: "3px 8px", borderRadius: "5px", margin: "2px 4px" },
    "& > ul > li[aria-selected]": { backgroundColor: "var(--accent-soft)", color: "var(--ink-1)" },
    "& .cm-completionLabel": { color: "var(--syn-command)" },
    "& .cm-completionDetail": { color: "var(--ink-3)", fontStyle: "normal", marginLeft: "8px", fontFamily: "var(--font-ui)" },
    "& .cm-completionMatchedText": { textDecoration: "none", color: "var(--accent)", fontWeight: "600" },
  },
  ".cm-completionInfo": {
    fontFamily: "var(--font-ui)",
    padding: "6px 10px",
    color: "var(--ink-2)",
    backgroundColor: "var(--bg-3)",
    border: "1px solid var(--hair-2)",
    borderRadius: "var(--r-md)",
    boxShadow: "var(--shadow-2)",
  },
  ".cm-tooltip-lint": { padding: "4px 6px" },
  ".cm-diagnostic": { borderLeft: "3px solid var(--diag-info)", padding: "3px 8px", margin: "2px 0", borderRadius: "0 4px 4px 0", whiteSpace: "pre-wrap", fontFamily: "var(--font-ui)" },
  ".cm-diagnostic-error": { borderLeftColor: "var(--diag-error)" },
  ".cm-diagnostic-warning": { borderLeftColor: "var(--diag-warning)" },
  ".cm-diagnosticSource": { color: "var(--ink-4)", fontSize: "0.85em" },
  ".cm-panels": {
    backgroundColor: "var(--bg-2)",
    color: "var(--ink-1)",
    borderBottom: "1px solid var(--hair)",
    fontFamily: "var(--font-ui)",
    fontSize: "var(--text-sm)",
  },
  ".cm-panels.cm-panels-bottom": { borderTop: "1px solid var(--hair)", borderBottom: "none" },
  ".cm-panel.cm-search": { padding: "6px 8px" },
  ".cm-panel.cm-search input, .cm-panel.cm-search button, .cm-panel.cm-search label": {
    fontFamily: "var(--font-ui)",
    fontSize: "var(--text-xs)",
    color: "var(--ink-1)",
  },
  ".cm-panel.cm-search input": {
    backgroundColor: "var(--bg-3)",
    border: "1px solid var(--hair-2)",
    borderRadius: "6px",
    padding: "3px 6px",
    outline: "none",
  },
  ".cm-panel.cm-search input:focus": { borderColor: "var(--accent)" },
  ".cm-panel.cm-search button": {
    backgroundImage: "none",
    backgroundColor: "var(--bg-glass)",
    border: "1px solid var(--hair)",
    borderRadius: "6px",
    padding: "2px 8px",
    color: "var(--ink-2)",
    cursor: "pointer",
  },
  ".cm-panel.cm-search button:hover": { color: "var(--ink-1)", borderColor: "var(--hair-2)" },
  ".cm-panel.cm-search [name=close]": { color: "var(--ink-3)", fontSize: "16px", top: "4px", right: "6px" },
  ".cm-placeholder": { color: "var(--ink-4)", fontStyle: "italic" },
  ".cm-specialChar": { color: "var(--err)" },
  ".cm-snippetField": { backgroundColor: "var(--accent-soft)", borderRadius: "3px" },
  ".cm-snippetFieldPosition": { borderLeft: "1.5px solid var(--accent)" },
});
